// Baked-in default lists for the Grateful and Today views.
// No names, no identifying details. Anyone loading their own list on a device
// (via the "Edit list" sheet) overrides these for that device only.
(function () {
  window.PERSONAL_DEFAULTS = {
    grateful: [
      "The twenty minutes before anyone else in the house is awake.",
      "A skill that doesn't evaporate if the economy turns.",
      "Patients who come back after a session that didn't go well.",
      "The ICU years, which made most things stop feeling like emergencies.",
      "Signing the checks instead of waiting on one.",
      "My wife running the gym better than I would have.",
      "My kid's complete indifference to whether I had a productive day.",
      "My kid reading past the page count they agreed to.",
      "A partnership problem that's behind me instead of ahead of me.",
      "Coffee that is objectively mediocre and still does the job.",
      "That a bad month is a cash flow problem, not a survival one.",
      "Being able to turn down work I don't want.",
      "Learning a language badly, slowly, with nobody grading me.",
      "A body that shows up for the workout I didn't want to do.",
      "People who text back the same day.",
      "The stubbornness that got the paperwork signed, notarized, and mailed.",
      "Knowing what a 3am hospital hallway feels like and not being in one tonight.",
      "Boring days at the practice.",
      "Enough clinical hours behind me to trust my read on a room.",
      "Software that saves me the hour I used to spend on faxes.",
      "The nurses who taught me before anyone was paying me to know anything.",
      "A wife who tells me when the idea is bad.",
      "Building something my kids can see the inside of.",
      "Silence in the car.",
      "More than one language in my head.",
      "A book that takes three weeks and earns it.",
      "Friends I can go a year without calling and pick up mid-sentence.",
      "Being underestimated now and then.",
      "The version of me who decided to go back to school.",
      "Not needing to be the smartest person in the meeting.",
      "Work where the outcome is a person, not a metric.",
      "Students who ask questions I have to think about.",
      "That the worst day this month was administrative.",
      "Enough money that groceries aren't a decision.",
      "Clean water, boring plumbing, a house that stays warm.",
      "Being on the winning side of an argument I used to lose.",
      "Sleeping fine after a heavy clinical day.",
      "Work hours that still leave dinner with the kids intact.",
      "A license with my name on it that took years to earn.",
      "Getting older without getting bitter about it.",
      "People who said yes when I asked for something awkward.",
      "Films that hold up on a third watch.",
      "A hobby that costs me nothing but attention.",
      "My own handwriting on a plan that actually worked.",
      "Being trusted with things people don't tell anyone else.",
      "Days when nobody needs me to be impressive.",
      "The referral that came in without me chasing it.",
      "Old equipment, old furniture, old clothes that still work.",
      "Knowing exactly what I'd do if all of this fell apart.",
      "Being early enough in this that it's still being built."
    ],
    today: [
      "Do the one task I've already moved twice.",
      "Close the loop on the oldest thing sitting in my inbox.",
      "Write one paragraph for the site before opening messages.",
      "Ask my kid about their book instead of about their day.",
      "Take my kid outside for fifteen minutes with the phone inside.",
      "Lift, even if it's the short version.",
      "Ten minutes of Portuguese before the first call.",
      "Text the person I've been meaning to text for a month.",
      "Finish charting before dinner instead of after.",
      "Say no to one thing without explaining myself twice.",
      "Batch every phone call into a single block.",
      "Walk before opening the laptop.",
      "Eat lunch away from a screen.",
      "Send the invoice I haven't sent.",
      "Ask my wife what she needs this week, then actually do it.",
      "Draft the document I keep re-planning instead of writing.",
      "Read twenty pages before bed instead of scrolling.",
      "Give one patient the extra two minutes at the end.",
      "Fix one small workflow annoyance permanently.",
      "Call instead of text.",
      "Protect ninety minutes for the hardest thing, first.",
      "Give the student feedback that's specific enough to use.",
      "Clear the desk before I walk away from it.",
      "Ask for the referral instead of waiting for it.",
      "Write tomorrow's three priorities on paper before shutting down.",
      "Skip the second coffee and see what happens.",
      "Cook instead of ordering.",
      "Take the call standing up.",
      "Cancel one subscription I don't use.",
      "Follow up on the thing that's gone quiet.",
      "Compliment someone specifically enough that it lands.",
      "Leave at the hour I said I'd leave.",
      "Write down one clinical thing I learned today.",
      "Handle the paperwork I keep pretending isn't there.",
      "Spend thirty minutes on the business rather than in it.",
      "Ask a question in the meeting instead of making a statement.",
      "Look at the numbers I've been avoiding.",
      "Get on the floor with the kids instead of watching from the couch.",
      "Put the phone in another room for an hour.",
      "Move the credentialing item forward by one message.",
      "Take a ten minute walk after the last patient to end the workday.",
      "Say the uncomfortable thing, kindly, today rather than next week.",
      "Reschedule instead of canceling.",
      "Set out tomorrow's coffee, bag, and clothes tonight.",
      "Watch something with my wife without a second screen open.",
      "Write the SOP for the task I keep explaining out loud.",
      "Ask for what I want once, directly, without softening it.",
      "Take the stairs and park farther out, no ceremony about it.",
      "Give the day a hard stop at a specific hour and hold it.",
      "Let one thing be good enough and ship it."
    ]
  };
})();
